### ISSUE TITLE
DCM-Display ; Frontend 2 - Table for Menu Items (MenuItemsTable) for Epic #3

### ISSUE THREAD

**Issue by ttnguyen908** [ucsb-cs156-f24/proj-dining-f24-16#30]
Task **Frontend 2** for ;
- [EPIC: Dining Commons Menus displayed Instead of Placeholder](https://github.com/orgs/ucsb-cs156-f24/projects/53/views/1?pane=issue&itemId=87178932&issue=ucsb-cs156-f24%7Cproj-dining-f24-16%7C3)

__________________________________________________________________

# Description from Epic #3 
- The tasks for this task and epi interacts with [FEATURE: Users Set Their Aliases
](https://github.com/ucsb-cs156-f24/proj-dining-f24-16/issues/2) so read through that one first.
- These can be worked on in parallel.
- This epic takes the placeholder page described in [Epic #3](https://github.com/ucsb-cs156-f24/proj-dining-f24-16/issues/2) and fleshes it out with the menu items for a dining commons.

## User Story
- As a **User**.
- Can see the menu for any dining commons, for any day.
- Can see what's being served and put reviews for items once said feature is added.

__________________________________________________________________

# Frontend 2 - Table for Menu Items (MenuItemsTable) for Epic
- [ ] Build a table that can display menu items as returned by the GET /api/diningcommons/:date-time/:dining-commons-code/:meal endpoint. 
- [ ] Include a column with a button called "Review this item" which for now just brings up a `window.alert("Feature coming soon!") message.
- [ ] The table should have columns for DiningCommonsCode, Meal, Item, Station, and id (the id from the MenuItems table)
