### ISSUE TITLE
DCM-Display ; Frontend 4 - On Placeholder Page for /diningCommons/:dining-commons-code, Placeholder Page Created in #2 + Add date-time selector for Epic #3

### ISSUE THREAD

**Issue by ttnguyen908** [ucsb-cs156-f24/proj-dining-f24-16#31]
Task **Frontend 4** for ;
- [EPIC: Dining Commons Menus displayed Instead of Placeholder](https://github.com/orgs/ucsb-cs156-f24/projects/53/views/1?pane=issue&itemId=87178932&issue=ucsb-cs156-f24%7Cproj-dining-f24-16%7C3)

__________________________________________________________________

# Description from Epic #3 
- The tasks for this task and epi interacts with [FEATURE: Users Set Their Aliases
](https://github.com/ucsb-cs156-f24/proj-dining-f24-16/issues/2) so read through that one first.
- These can be worked on in parallel.
- This epic takes the placeholder page described in [Epic #3](https://github.com/ucsb-cs156-f24/proj-dining-f24-16/issues/2) and fleshes it out with the menu items for a dining commons.

## User Story
- As a **User**.
- Can see the menu for any dining commons, for any day.
- Can see what's being served and put reviews for items once said feature is added.

__________________________________________________________________

# Frontend 4 - On Placeholder Page for /diningCommons/:dining-commons-code, Placeholder Page Created in #2 + Add date-time selector for Epic #3
- [ ] Add a date-time selector that defaults to the current date and time.
- [ ] Retrieve the meals from the endpoint GET /api/diningcommons/:date-time/:dining-commons-code and display those meals in a MealsTable.
- [ ] Have a button that allows the user to update the meals if / when the date is changed.
> - Each line in the meals table should go to the page /diningcommons/:date-time/:dining-commons-code/:meal which should be the placeholder created in Frontend 3 above.
